const login = document.querySelector(".ioj");
const chk = document.querySelector(".chk");
const users = document.getElementById("user");
const Password = document.getElementById("pass");

login.addEventListener("click", () => {
    
    if(document.getElementById("user").value=="nad" && document.getElementById("pass").value=="n1234" ){
    document.location='n2.html'}
    
    
    
  });



